# Generated by Django 4.2.7 on 2025-09-08 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='semester',
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Décocher pour masquer temporairement', verbose_name='Visible pour les étudiants'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Réservé aux fonctionnalités payantes futures', verbose_name='Contenu premium'),
        ),
    ]
