# Generated by Django 4.2.7 on 2025-09-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_document_external_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('COURS', 'Cours'), ('TD', 'Travaux dirigés'), ('TP', 'Travaux pratiques'), ('ARCHIVE', 'Archive')], default='COURS', max_length=15, verbose_name='Type de document'),
        ),
    ]
