# Generated by Django 4.2.7 on 2025-09-13 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_alter_document_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('download', 'Téléchargement'), ('view', 'Consultation'), ('favorite', 'Favori ajouté'), ('unfavorite', 'Favori retiré')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.document')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité utilisateur',
                'verbose_name_plural': 'Activités utilisateurs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='courses_use_user_id_cdbb0f_idx'), models.Index(fields=['action', '-created_at'], name='courses_use_action_f6b300_idx'), models.Index(fields=['document', '-created_at'], name='courses_use_documen_0fefc3_idx')],
            },
        ),
    ]
