# Generated by Django 4.2.7 on 2025-09-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_add_user_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Consultations'),
        ),
    ]
