# Generated by Django 4.2.7 on 2025-10-02 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_add_view_count_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('duration_minutes', models.PositiveIntegerField(default=15, help_text='Temps alloué pour compléter le quiz', verbose_name='durée (minutes)')),
                ('passing_score', models.DecimalField(decimal_places=2, default=10.0, help_text='Score minimum pour réussir (sur 20)', max_digits=5, verbose_name='score minimum')),
                ('max_attempts', models.PositiveIntegerField(default=3, help_text="Nombre de fois que l'étudiant peut passer le quiz", verbose_name='tentatives maximales')),
                ('show_correction', models.BooleanField(default=True, help_text='Montrer les bonnes réponses après soumission', verbose_name='afficher la correction')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('available_from', models.DateTimeField(blank=True, null=True, verbose_name='disponible à partir de')),
                ('available_until', models.DateTimeField(blank=True, null=True, verbose_name="disponible jusqu'à")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.subject', verbose_name='matière')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('ABANDONED', 'Abandonné')], default='IN_PROGRESS', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='score')),
                ('attempt_number', models.PositiveIntegerField(verbose_name='numéro de tentative')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='courses.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tentative de quiz',
                'verbose_name_plural': 'tentatives de quiz',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'quiz', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='question')),
                ('question_type', models.CharField(choices=[('QCM', 'Choix multiple (une réponse)'), ('TRUE_FALSE', 'Vrai/Faux'), ('MULTIPLE', 'Choix multiples (plusieurs réponses)')], default='QCM', max_length=20, verbose_name='type de question')),
                ('points', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='points')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('explanation', models.TextField(blank=True, help_text='Explication de la bonne réponse (optionnel)', verbose_name='explication')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz', verbose_name='quiz')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='texte')),
                ('is_correct', models.BooleanField(default=False, verbose_name='réponse correcte')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'choix',
                'verbose_name_plural': 'choix',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='correct')),
                ('points_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='points obtenus')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question')),
                ('selected_choices', models.ManyToManyField(to='courses.choice', verbose_name='choix sélectionnés')),
            ],
            options={
                'verbose_name': 'réponse étudiant',
                'verbose_name_plural': 'réponses étudiants',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
