# Generated by Django 4.2.7 on 2025-10-06 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_quiz_quizattempt_question_choice_studentanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='passing_score',
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Pourcentage minimum requis pour réussir (ex: 50 = 50%, 60 = 60%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='pourcentage de réussite'),
        ),
    ]
