# Generated by Django 4.2.7 on 2025-10-12 17:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_quiz_quizattempt_question_choice_studentanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Non démarré'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('ARCHIVED', 'Archivé')], default='NOT_STARTED', max_length=20, verbose_name='statut')),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=20, verbose_name='priorité')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='échéance')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='terminé le')),
                ('progress_percentage', models.IntegerField(default=0, help_text='Calculé automatiquement basé sur les tâches', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progression (%)')),
                ('color', models.CharField(default='#3B82F6', help_text="Couleur hex pour l'interface (ex: #3B82F6)", max_length=7, verbose_name='couleur')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='favori')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage personnalisé", verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, help_text='Matière liée au projet (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_projects', to='courses.subject', verbose_name='matière associée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_projects', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'projet étudiant',
                'verbose_name_plural': 'projets étudiants',
                'ordering': ['-is_favorite', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('TODO', 'À faire'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminé')], default='TODO', max_length=20, verbose_name='statut')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='échéance')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='terminée le')),
                ('order', models.IntegerField(default=0, help_text='Position dans la colonne Kanban', verbose_name='ordre')),
                ('is_important', models.BooleanField(default=False, help_text='Marquer comme prioritaire', verbose_name='importante')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='temps estimé (heures)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.studentproject', verbose_name='projet')),
            ],
            options={
                'verbose_name': 'tâche de projet',
                'verbose_name_plural': 'tâches de projet',
                'ordering': ['order', '-is_important', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentproject',
            index=models.Index(fields=['user', 'status'], name='courses_stu_user_id_0c64c2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentproject',
            index=models.Index(fields=['user', '-created_at'], name='courses_stu_user_id_ccdc9b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentproject',
            index=models.Index(fields=['due_date'], name='courses_stu_due_dat_1c7a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project', 'status'], name='courses_pro_project_817927_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['project', 'order'], name='courses_pro_project_a4393d_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['due_date'], name='courses_pro_due_dat_7b804f_idx'),
        ),
    ]
