# Generated by Django 4.2.7 on 2025-11-12 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_studentproject_projecttask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='passing_percentage',
        ),
    ]
