# Generated by Django 4.2.7 on 2025-11-12 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_quiz_passing_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passing_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Pourcentage minimum requis pour réussir (ex: 50 = 50%, 60 = 60%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='pourcentage de réussite'),
        ),
    ]
