# Generated by Django 4.2.7 on 2025-10-19 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0008_studentproject_projecttask_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='notifications activées')),
                ('new_content_enabled', models.BooleanField(default=True, verbose_name='nouveaux contenus (cours/TD/TP)')),
                ('quiz_enabled', models.BooleanField(default=True, verbose_name='nouveaux quiz')),
                ('deadline_reminders_enabled', models.BooleanField(default=True, verbose_name='rappels de deadlines')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='mode silencieux activé')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='début mode silencieux')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='fin mode silencieux')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'préférence de notification',
                'verbose_name_plural': 'préférences de notifications',
            },
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='token FCM')),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20, verbose_name="type d'appareil")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'token FCM',
                'verbose_name_plural': 'tokens FCM',
                'ordering': ['-last_used'],
            },
        ),
        migrations.CreateModel(
            name='SubjectPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='notifications activées pour cette matière')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='courses.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'préférence matière',
                'verbose_name_plural': 'préférences matières',
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_document', 'Nouveau document'), ('new_quiz', 'Nouveau quiz'), ('quiz_closing', 'Quiz bientôt fermé'), ('project_reminder', 'Rappel projet')], max_length=50, verbose_name='type')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('data', models.JSONField(blank=True, help_text='IDs des documents, quiz, projets, etc.', null=True, verbose_name='données supplémentaires')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False, verbose_name='lu')),
                ('clicked', models.BooleanField(default=False, verbose_name='cliqué')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', '-sent_at'], name='notificatio_user_id_bba705_idx'), models.Index(fields=['user', 'read'], name='notificatio_user_id_23638e_idx')],
            },
        ),
    ]
