# Generated by Django 4.2.7 on 2025-09-06 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: INFO, MATH, BIO, etc.', max_length=10, unique=True, verbose_name='code')),
                ('name', models.CharField(help_text='Ex: Informatique, Mathématiques, etc.', max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, help_text='Description de la filière', verbose_name='description')),
                ('department', models.CharField(blank=True, help_text='Département ou faculté', max_length=100, verbose_name='département')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage", verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_majors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'filière',
                'verbose_name_plural': 'filières',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: L1, L2, M1, etc.', max_length=10, unique=True, verbose_name='code')),
                ('name', models.CharField(help_text='Ex: Licence 1, Master 1, etc.', max_length=50, verbose_name='nom')),
                ('description', models.TextField(blank=True, help_text='Description optionnelle du niveau', verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = premier)", verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'niveau',
                'verbose_name_plural': 'niveaux',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.level', verbose_name='niveau'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.major', verbose_name='filière'),
        ),
    ]
